feat: save many reports

diff --git a/.github/workflows/system_tests.yml b/.github/workflows/system_tests.yml
--- a/.github/workflows/system_tests.yml
+++ b/.github/workflows/system_tests.yml
@@ -26,24 +26,77 @@ jobs:
           path: playwright-report/
           retention-days: 30
   
-  publishTestResults:
-    name: "Publish Test Results"
-    needs: system-tests
-    runs-on: ubuntu-latest
-    if: always()
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v2
-        id: download
+  # publishTestResults:
+  #   name: "Publish Test Results"
+  #   needs: system-tests
+  #   runs-on: ubuntu-latest
+  #   if: always()
+  #   steps:
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v2
+  #       id: download
 
-      - name: Publish to GH Pages
-        if: always()
-        uses: peaceiris/actions-gh-pages@v3.7.3
+  #     - name: Publish to GH Pages
+  #       if: always()
+  #       uses: peaceiris/actions-gh-pages@v3.7.3
+  #       with:
+  #         external_repository: novasamatech/spektr-reports
+  #         publish_branch: main
+  #         personal_token: ${{ secrets.CREATE_TAG_PAT }}
+  #         publish_dir: ${{steps.download.outputs.download-path}}
+  #         keep_files: true
+  #         user_name: "github-actions[bot]"
+  #         user_email: "github-actions[bot]@users.noreply.github.com"
+  
+  publish_report:
+    name: Publish HTML Report
+    # using always() is not ideal here, because it would also run if the workflow was cancelled
+    if: success() || needs.system-tests.result == 'failure'
+    needs: [system-tests]
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    env:
+      # Unique URL path for each workflow run attempt
+      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
+    steps:
+      - name: Checkout GitHub Pages Branch
+        uses: actions/checkout@v2
         with:
-          external_repository: novasamatech/spektr-reports
-          publish_branch: main
-          personal_token: ${{ secrets.CREATE_TAG_PAT }}
-          publish_dir: ${{steps.download.outputs.download-path}}
-          keep_files: true
-          user_name: "github-actions[bot]"
-          user_email: "github-actions[bot]@users.noreply.github.com"
+          repository: novasamatech/spektr-reports
+          ref: main
+          token: ${{ secrets.CREATE_TAG_PAT }}
+      - name: Set Git User
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+      - name: Download zipped HTML report
+        uses: actions/download-artifact@v2
+        with:
+          name: playwright-report
+          path: ${{ env.HTML_REPORT_URL_PATH }}
+      - name: Push HTML Report
+        timeout-minutes: 3
+        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+        # this is necessary when this job is running at least twice at the same time (e.g. through two pushes at the same time)
+        run: |
+          git add .
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+  
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+  
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+      - name: Output Report URL as Worfklow Annotation
+        run: |
+          FULL_HTML_REPORT_URL=https://ysfaran.github.io/playwright-gh-actions-gh-pages/$HTML_REPORT_URL_PATH
+  
+          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
